# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10a77b9306aa605b89ee11105b3cb0599cf4680b5cf8d9dd920dcdd56f28f7a509f00085e3bab9535a1efd3081ed1e7db95987928c6a0139a52b8c26ed831474

test:
  secret_key_base: be449143ca1a1abfe398022c6fab4576ede86d6e82a1370656cc0c407e2502054da5bcaf8d4f61d6114fea81b56ab1dcfee4458f3bd96954c84caf3c7c70d2a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
